### ISSUE TITLE
Crashes on start: AttributeError: 'netfilterqueue.NetfilterQueue' object has no attribute 'get_fd'

### ISSUE THREAD

**Issue by mydockergit** [fireeye/flare-fakenet-ng#129]
After the installation I ran it on Kali and received the following error:
```
root@kali:~/flare-fakenet-ng/fakenet# python fakenet.py 

  ______      _  ________ _   _ ______ _______     _   _  _____
 |  ____/\   | |/ /  ____| \ | |  ____|__   __|   | \ | |/ ____|
 | |__ /  \  | ' /| |__  |  \| | |__     | |______|  \| | |  __
 |  __/ /\ \ |  < |  __| | . ` |  __|    | |______| . ` | | |_ |
 | | / ____ \| . \| |____| |\  | |____   | |      | |\  | |__| |
 |_|/_/    \_\_|\_\______|_| \_|______|  |_|      |_| \_|\_____|

                        Version 1.4.9
  _____________________________________________________________
                   Developed by FLARE Team
  _____________________________________________________________
                                               
08/20/19 10:47:01 AM [           FakeNet] Loaded configuration file: configs/default.ini
08/20/19 10:47:01 AM [          Diverter] Capturing traffic to packets_20190820_104701.pcap
08/20/19 10:47:01 AM [               FTP] >>> starting FTP server on 0.0.0.0:21, pid=3983 <<<
08/20/19 10:47:01 AM [               FTP] concurrency model: multi-thread
08/20/19 10:47:01 AM [               FTP] masquerade (NAT) address: None
08/20/19 10:47:01 AM [               FTP] passive ports: 60000->60010
Traceback (most recent call last):
  File "fakenet.py", line 437, in <module>
    main()
  File "fakenet.py", line 412, in main
    fakenet.start()
  File "fakenet.py", line 243, in start
    self.diverter.start()
  File "/root/flare-fakenet-ng/fakenet/diverters/diverterbase.py", line 681, in start
    return self.startCallback()
  File "/root/flare-fakenet-ng/fakenet/diverters/linux.py", line 155, in startCallback
    ok = q.start()
  File "/root/flare-fakenet-ng/fakenet/diverters/linutil.py", line 156, in start
    self._nfqueue.get_fd(), socket.AF_UNIX, socket.SOCK_STREAM)
AttributeError: 'netfilterqueue.NetfilterQueue' object has no attribute 'get_fd'
```
I used Kali image from offensive-security website.
I cloned the git for the open source and ran it.

**Comment by mydockergit** [comment]
Solved it by using this link:
https://stackoverflow.com/questions/55693586/netfilterqueue-installation-in-kali

`apt-get install build-essential python-dev libnetfilter-queue-dev`
